version: "3.8"

services:
  api:
    build: .
    volumes:
      - ./strategy_metadata:/app/strategy_metadata:ro  # Mount read-only
    ports:
      - "8000:8000"
    command: uvicorn run_api:app --host 0.0.0.0 --port 8000
